# Replace values with your SonarCloud identifiers
sonar.projectKey=AlvaroPerdigonG_tfg-ticketing-devops
sonar.organization=alvaroperdigong

sonar.sources=ticketing-backend/src/main,ticketing-frontend/src
sonar.tests=ticketing-backend/src/test,ticketing-frontend/src

sonar.java.binaries=ticketing-backend/target/classes
sonar.test.inclusions=ticketing-frontend/src/**/*.test.ts,ticketing-frontend/src/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/target/**
